# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59f46cca472a55c1c9fa50417561d54628591120f5cc2d38fe9f5eb1dacf640e5df68a97bc83b2898bae6c92259ee11408a89bab40abb59a3d4787ed2d2ccc92

test:
  secret_key_base: 9237ea6a131b95f224893fed3814b1f2195434649c65d51c364ab96ef5291964509aa9e0e28f5c12cb3705df7ae939a9204407f9f4c60482fb7f7068da2a69c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
